// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzT9Fv22iZPmM1QSRSr-jowhh8x62HaZQ',
    appId: '1:705912763125:web:e647672c68c4fd5005cbbc',
    messagingSenderId: '705912763125',
    projectId: 'whatsappclone-90855',
    authDomain: 'whatsappclone-90855.firebaseapp.com',
    storageBucket: 'whatsappclone-90855.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPJ8Mvs1aTF6ELkMjLt1v1yNT4n8KRl58',
    appId: '1:705912763125:android:b3967ce18e10518205cbbc',
    messagingSenderId: '705912763125',
    projectId: 'whatsappclone-90855',
    storageBucket: 'whatsappclone-90855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb8lOfsT7701x-1XprtSFPnw6mWKFyG3c',
    appId: '1:705912763125:ios:5675fb38916d4b1705cbbc',
    messagingSenderId: '705912763125',
    projectId: 'whatsappclone-90855',
    storageBucket: 'whatsappclone-90855.appspot.com',
    iosBundleId: 'com.example.messagingWhatsappApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb8lOfsT7701x-1XprtSFPnw6mWKFyG3c',
    appId: '1:705912763125:ios:5675fb38916d4b1705cbbc',
    messagingSenderId: '705912763125',
    projectId: 'whatsappclone-90855',
    storageBucket: 'whatsappclone-90855.appspot.com',
    iosBundleId: 'com.example.messagingWhatsappApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzT9Fv22iZPmM1QSRSr-jowhh8x62HaZQ',
    appId: '1:705912763125:web:44e15201a975176205cbbc',
    messagingSenderId: '705912763125',
    projectId: 'whatsappclone-90855',
    authDomain: 'whatsappclone-90855.firebaseapp.com',
    storageBucket: 'whatsappclone-90855.appspot.com',
  );
}
